# Generated by Django 4.1.3 on 2022-11-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_driverprofile_workday_delete_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='last_name',
        ),
        migrations.AddField(
            model_name='workday',
            name='bus_number',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workday',
            name='end_mileage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workday',
            name='start_mileage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workday',
            name='work_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='workday',
            name='work_start',
            field=models.DateTimeField(),
        ),
    ]
