# Generated by Django 4.1.3 on 2022-11-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_driverprofile_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='workday',
            name='bus_number',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
