# Generated by Django 4.1.3 on 2022-11-28 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_workday_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('registration_number', models.CharField(max_length=10)),
                ('total_odometer', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='workday',
            name='bus_number',
        ),
        migrations.AddField(
            model_name='workday',
            name='bus',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bus_number', to='main.bus'),
        ),
    ]
